general.import = [
 "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

general.live_config_reload = true

[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
blink_interval = 500
blink_timeout = 5
unfocused_hollow = false

[cursor.style]
blinking = "Off"
shape = "Block"

[env]
TERM = "xterm-256color"

[window]
position.x = 150 
position.y = 165
padding.x = 20
padding.y = 20
dynamic_padding = true
dynamic_title = true

decorations = "Buttonless"

opacity = 1.0
blur = true 

option_as_alt = "Both"

[font]
normal.family = "JetBrainsMono Nerd Font" 

size = 18

[window.dimensions]
columns = 120
lines = 30 
